name: CI dynamics-sales-test-console-app

on:
  workflow_call:
  push:
    branches: [ "master" ]
    paths:
      - 'src/DynamicsToolConsole/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/DynamicsToolConsole/**'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Project_Path: ./src/DynamicsToolConsole/DynamicsToolConsole.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    - name: Build project
      run: dotnet build $env:Project_Path --configuration $env:Configuration 
      env:
       Configuration: ${{ matrix.configuration }}

    # - name: Publish project as Windows app
    #   run: dotnet publish $env:Project_Path --configuration $env:Configuration /p:PublishSingleFile=true /p:DebugType=None -r win-x64 --sc true
    #   env:
    #    Configuration: ${{ matrix.configuration }}    

    # - name: Publish project as Linux app
    #   run: dotnet publish $env:Project_Path --configuration $env:Configuration /p:PublishSingleFile=true /p:DebugType=None -r linux-x64 --sc true
    #   env:
    #    Configuration: ${{ matrix.configuration }}    

    # - name: Publish project as MacOS app
    #   run: dotnet publish $env:Project_Path --configuration $env:Configuration /p:PublishSingleFile=true /p:DebugType=None -r osx-x64 --sc true
    #   env:
    #    Configuration: ${{ matrix.configuration }}    
